### ISSUE TITLE
GC - Delete outdated branches

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync#10]
Whenever the root version vector of a branch changes, we should find all branches that are older (happens-before) than this branch and delete them. This would automatically delete any unneeded blocks referenced by those branches thus counting as a form of garbage collection.

**Comment by inetic** [comment]
I think we already do this? There used to be an issue where we did not delete incomplete branches, but that one is fixed now.

Maybe we also had a problem where an old snapshot wouldn't get delete when a new snapshot was created, but IIRC you already fixed it in the past. I also did a quick check and it seems to be fixed.

**Comment by madadam** [comment]
We do delete old snapshots within a single branch but maybe we should also delete snapshots across branches - so if there is a snapshot of some branch with version vector `v`, then we should delete all snapshots that have their vv < `v` regardless of which branch they are from.

**Comment by madadam** [comment]
Closed inhttps://github.com/equalitie/ouisync/commit/168794a28a4092ab0f3749df175ba512f34ddc20
