### ISSUE TITLE
Possibly unwanted information leak in peer-exchange

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#105]
The peer exchange protocol as is implemented shares all found peer IP addresses with everyone. Say, for example that I have two repositories R<sub>1</sub> and R<sub>2</sub> and I share repository R<sub>1</sub> with peer P<sub>1</sub> and repository R<sub>2</sub> with P<sub>2</sub>. In the current PEX implementation my node informs R<sub>1</sub> about IP of R<sub>2</sub> and vice versa, even if the two don't have any repository in common. This "information leak" may be undesirable and if so, PEX should only inform other peers about IPs sharing the same repo.

**Comment by madadam** [comment]
Fixed in https://github.com/equalitie/ouisync/commit/2907d2295ff83b9443827dbd3dc9ed662d5a57c4
