### ISSUE TITLE
Throttle the `RootNode` responses on received blocks

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync#125]
Currently every time we receive a new block, we send a `RootNode` response to all our peers. When there is a lot of received blocks (e.g. when syncing a large file) this generates excessive network traffic. We should throttle these message somehow.

NOTE we should do the throttling both on the sender side (to avoid the excessive traffic) and on the receiver side (to account for spam).

**Comment by inetic** [comment]
Fixed in https://github.com/equalitie/ouisync/commit/a36180c52a3f35abeba4f9659654f000596bd344
