### ISSUE TITLE
Detect ungraceful disconnection even with no repos

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync#129]
If there are no repositories we don't send or receive anything on any established peer connections and so we don't detect disconnection either. This is an issue if we were connected to a peer who ungracefully disconnected and then it tries to connect again: we never detected the disconnect and so we consider the peer as still connected and so we reject the new connection attempt as duplicate.

Note this problem occurs only if we have no repositories and it resolves itself immediately once we create at least one repository so fixing it is low priority.

**Comment by inetic** [comment]
Should be fixed by merge https://github.com/equalitie/ouisync/commit/58747ddea08c417f52f7f4042321888e1040528a
