### ISSUE TITLE
Usage statistics

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync#134]
Gather anonymized usage statistics on the server. 

Initially it should be enough to just gather amount of downloaded / uploaded data per unique ip address and then aggregate it by country

Ideas:

Use something like [prometheus](https://prometheus.io/) to gather the data, then visualize with e.g. [grafana](https://grafana.com/). That way the actual logic in ouisync would be minimal as all the heavy lifting would be provided by those external tools. Plus in the future we can extend it to gather more data if we want. All we need to do it to collect the data and make it available for prometheus (either serve it for scraping or push it).

**Comment by jnny** [comment]
@madadam have you discussed implementing ouisync metrics with keith? this sounds like our existing setup for ouinet metrics - we could set up a ouisync set of dashboards in https://mias.ouinet.work/..

**Comment by madadam** [comment]
Work on the ouisync side is now done. Still need to hook it up to mias.

**Comment by madadam** [comment]
grafana dashboard on mias created, closing as done.
