### ISSUE TITLE
Can-we/should-we prevent overwriting files when two replicas are connected?

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#163]
We currently support the case where if two replicas are both offline and they modify the same file, then on sync they create a divergent file versions, but what if they are both online and connected? Consider this scenario:

1. Replica A and B are connected
2. Both replicas open file `/foo.txt`
3. A writes "text from A" into `/foo.txt` and saves the it
4. A and B syncs
5. B writes "text from B" into `/foo.txt` and saves it

The result is that the file `/foo.txt` contains "text from B" in it.

Perhaps we can do better: when a replica opens a file, it remembers the vv (version vector) in the file handle and when it saves the file, it compares the vv in the file handle with the one in the repo. If they diverge then create a divergent copy.

**Comment by madadam** [comment]
It should already work like that. Have you tested it? The way its implemented is different though: open files are treated specially and never overwritten during merge.

**Comment by inetic** [comment]
I haven't tested, I though we didn't have any mechanism to prevent overwriting in this case so created a ticket to not forget about it.
