### ISSUE TITLE
Store the DEVICE_ID in a human readable file instead of SqLite

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#19]
The DEVICE_ID is currently stored in an SqLite database separate from the main repository SqLite database.

It might make sense to store it in a plaintext file instead because then we could also write to the file some comments explaining what the DEVICE_ID is and why the user should be careful when migrating the repository from one device to another (the user should either not migrate the database with DEVICE_ID, or ensure it's no longer used on the replica from where it's being migrated).

On the other hand, in the future we might want to have more "per device" information stored somewhere, in which case we'd need to re-introduce this database. So this change should be settle first before we implement it.

**Comment by madadam** [comment]
>  in the future we might want to have more "per device" information stored somewhere, in which case we'd need to re-introduce this database

We can store the info in the config file as well

**Comment by inetic** [comment]
I'm starting to think that we won't really need to store anything outside of the main sqlite database except for the DEVICE_ID. Or in other words, we can store everything we need in the metadata table and if there is anything device specific, we can use the DEVICE_ID to disambiguate it as that's what the DEVICE_ID is for anyway.

**Comment by inetic** [comment]
Should be fixed here https://github.com/equalitie/ouisync/commit/29f6631bf400094188e9bca38c410c04082185d1
