### ISSUE TITLE
Failed forking of a file may result in dangling blocks.

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#26]
Right now (commit 62763ec1) when forking a file, we:

1. first [fork the blob](https://github.com/equalitie/ouisync/blob/f7a61a41f9fecc17f137f0d98e4b9683efd10b42/lib/src/file.rs#L118-L120)
2. and then [update the parents](https://github.com/equalitie/ouisync/blob/f7a61a41f9fecc17f137f0d98e4b9683efd10b42/lib/src/file.rs#L121)

If it was to happen that the computer crashes right after the blob forking step, the database will end up storing dangling block that will never be removed.

Doing the two above steps in a single DB transaction wold avoid the problem.

**Comment by madadam** [comment]
Closed in https://github.com/equalitie/ouisync/commit/a690b97ceddf6892203f40ea3e6a5461c93cf439
