### ISSUE TITLE
When `--port` is not specified, try to open on a last used port

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#27]
This way (mainly app) users can set up port forwarding manually if they don't want to or can't use UPnP.

**Comment by inetic** [comment]
This should mostly be fixed by 4e3354983e281b5deffc4399f45db6044a698bbb. However, I'll keep this open as it's currently done only for the TCP listening socket and we should to the same for the UDP one we use for BitTorrent DHT.

**Comment by madadam** [comment]
Grabbing this one.
