### ISSUE TITLE
Spam log from btdht

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#29]
Not sure whether this is happening with CLI as well, but on Android there is quite a bit of log messages about failing to connect to bogus bittorrent nodes. Most of them are of the form

```
02-18 15:07:15.542 19151 27317 E flutter-ouisync: Failed to handle incoming message: received unsolicited response (/home/user/.cargo/git/checkouts/btdht-d635c7480f6ffbef/a1b0468/src/worker/handler.rs:115)
```
or
```
02-18 15:07:18.043 19151 27313 E flutter-ouisync: Failed to handle incoming message: invalid bencode data (/home/user/.cargo/git/checkouts/btdht-d635c7480f6ffbef/a1b0468/src/worker/handler.rs:115)
```

Those are most likely BitTorrent lurkers and we're not really interested in them

**Comment by madadam** [comment]
Fixed in https://github.com/equalitie/ouisync/commit/cbd95e9ab7b63a3dc2a3cae118565973d5e3c025
