### ISSUE TITLE
Removing a file does not create a local branch and fails with PermissionDenied

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#30]
It is because branches are created "lazily" and when the user tries to delete a branch, the code internally creates the JointDirectory structure with the `local_branch` member set to `None`.

Then calling the `JointDirectory::remove_entry` on such joint directory will fail because it "thinks" that we don't have a local branch and thus not having permission to write to it.

**Comment by madadam** [comment]
What are the exact reproduction steps for this? Is it something like this:
1. Alice creates a repository and creates a file in it
2. Bob syncs with Alice
3. Alice deletes the repository
4. Alice syncs with Bob
5. Alice tries to delete the previously created file
?

**Comment by inetic** [comment]
It's simpler:

1. Alice creates a repository, creates a file `/foo` in it and sends write token to Bob
2. Bob syncs with the repository and (before doing anything else) attempts to delete the file Alice created

Bob will get the abovementioned `PermissionDenied` error.

However, if Bob creates any other file (say, `/bar`) and _then_ tries to delete `/foo`, that will work. It is because when creating `/bar`, Bob also created a local branch which will then be used when doing the `rm ./foo` operation.
