### ISSUE TITLE
"Or later" license as opposed to specifically GPLv3-only?

### ISSUE THREAD

**Issue by comradekingu** [equalitie/ouisync#37]
Instead of GPLv3-only in https://hosted.weblate.org/projects/ouisync/android-strings/#information
a GPLv3-or-later allows moving to other compatible licenses/upgrades.

**Comment by madadam** [comment]
Hello, thanks for the suggestion. This repository is for the ouisync library which doesn't contain any user-facing strings and so has no translations. You probably want to create the issue in [ouisync app](https://github.com/equalitie/ouisync-app/) instead.
