### ISSUE TITLE
Bug: file removed by one replica appears as having 0 bytes in another replica

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync#57]
Steps to reproduce: create two replicas, create a file in one and wait until it syncs with the other. Remove the file in the replica that created it. Observe how the file briefly disappears in the other replica but the appears again with 0 size.

**Comment by madadam** [comment]
This bug is possibly caused by issues with the directory cache. Addressing #60 might fix this.

**Comment by madadam** [comment]
#60 has been completed but this bug still seems to persist :disappointed:

**Comment by inetic** [comment]
Fixed since https://github.com/equalitie/ouisync/commit/cf78ed92ca15aee01fc810859b758c423a666d69
