### ISSUE TITLE
Attempt to reconnect to a lost peer with explicitly provided address 

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync#64]
When we connect to a peer by explicitly specifying their peer address (using the `--peers` option) and the peer disconnects and later reconnects on the same address/port, we currently don't try to reconnect to them. We probably should.

**Comment by inetic** [comment]
Should be fixed by https://github.com/equalitie/ouisync/commit/5361deb7e6e6138a8dee56539d87daaa4db2e4e7
