### ISSUE TITLE
The temporary `received_inner_nodes` table disappears 

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#69]
The `received_inner_nodes` table seem to disappear during runtime. To reproduce:

* Start a new repository on a PC and share it to Android.
* Copy two or three files on PC into the repository (sequentially).
* At some point Android log will start spitting these errors:

```
E/flutter-ouisync(18798):   2022-08-10T12:47:05.322806Z ERROR  error: fatal error
E/flutter-ouisync(18798):     at lib/src/network/client.rs:187
E/flutter-ouisync(18798):     in handle_inner_nodes with nodes.hash: 64ca2d..
E/flutter-ouisync(18798):     in client
E/flutter-ouisync(18798):     in link with local_id: 1
E/flutter-ouisync(18798):     in message_broker with this_runtime_id: 962323.., that_runtime_id: addb42..
E/flutter-ouisync(18798):     in connection with peer_source: LocalDiscovery, addr: Quic(192.168.0.136:65521)
E/flutter-ouisync(18798): 
E/flutter-ouisync(18798):   2022-08-10T12:47:05.323014Z ERROR  error: database error
E/flutter-ouisync(18798):     at lib/src/network/client.rs:61
E/flutter-ouisync(18798):     in client
E/flutter-ouisync(18798):     in link with local_id: 1
E/flutter-ouisync(18798):     in message_broker with this_runtime_id: 962323.., that_runtime_id: addb42..
E/flutter-ouisync(18798):     in connection with peer_source: LocalDiscovery, addr: Quic(192.168.0.136:65521)
E/flutter-ouisync(18798): 
E/flutter-ouisync(18798):   2022-08-10T12:47:05.325639Z ERROR  Failed to cleanup ReceiveFilter(client_id: 0): Db(Query(Database(SqliteError { code: 1, message: "no such table: received_inner_nodes" })))
E/flutter-ouisync(18798):     at lib/src/index/receive_filter.rs:123
```

The error at `lib/src/network/client.rs:187` originates from [`index/mod.rs:247`](https://github.com/equalitie/ouisync/blob/6e8c6dbc92934c0b085d239d97f007959be298fd/lib/src/index/mod.rs#L247) and it's the same one as the one from [`index/receive_filter.rs:123`](https://github.com/equalitie/ouisync/blob/6e8c6dbc92934c0b085d239d97f007959be298fd/lib/src/index/receive_filter.rs#L123) shown above:

`Db(Query(Database(SqliteError { code: 1, message: "no such table: received_inner_nodes" })))`

**Comment by inetic** [comment]
I think even before that error above I also see:

```
E/flutter-ouisync(21339):   2022-08-10T13:49:25.211154Z ERROR  error: database error
E/flutter-ouisync(21339):     at lib/src/repository/worker.rs:292
E/flutter-ouisync(21339):     in scan with mode: RequireAndCollect
E/flutter-ouisync(21339):     in worker with local_id: 1
```
It somes from [`repository/worker.rs:294`](https://github.com/equalitie/ouisync/blob/master/lib/src/repository/worker.rs#L294) and the particular error is:

`Db(Query(Database(SqliteError { code: 1, message: "no such table: unreachable_blocks" })))`

**Comment by madadam** [comment]
This probably happens because the db connection gets dropped for some reason and then re-established. Temporary tables exists only within the db connection which created them. 

There are multiple potential fixes: 
1. Figure out why the connection gets dropped and prevent it. Possibly something to do with the app going to sleep and back?
2. Create the temporary db tables in a [after_connect](https://docs.rs/sqlx/latest/sqlx/pool/struct.PoolOptions.html#method.after_connect) callback instead of in the migration.
3. Change them to non-temporary tables and wipe them out on startup

**Comment by madadam** [comment]
> I think even before that error above I also see...

`unreachable_blocks` is also temporary.

**Comment by inetic** [comment]
> because the db connection gets dropped

Where are these connections created?

**Comment by madadam** [comment]
Implicitly in `Pool::acquire`.  And on drop, they should be returned to the pool, not destroyed.

**Comment by inetic** [comment]
Quick fixed here https://github.com/equalitie/ouisync/commit/0958c884cd7ffcd4b186bdeff9197ca6ab7359fe

**Comment by madadam** [comment]
As of https://github.com/equalitie/ouisync/commit/f0a3e4d6bb6f13553e897d4b0e74b69040498a6b, those tables are not temporary anymore which implicitly fixes this problem. Closing.
